openapi: 3.0.0
info:
  version: 2018-04-23
  x-release: v4
  title: AWS MediaTailor Alerts#resourceArn API
  description: <p>Use the AWS Elemental MediaTailor SDKs and CLI to configure scalable ad insertion and linear channels. With MediaTailor, you can assemble existing content into a linear stream and serve targeted ads to viewers while maintaining broadcast quality in over-the-top (OTT) video applications. For information about using the service, including detailed information about the settings covered in this guide, see the <a href="https://docs.aws.amazon.com/mediatailor/latest/ug/">AWS Elemental MediaTailor User Guide</a>.</p> <p>Through the SDKs and the CLI you manage AWS Elemental MediaTailor configurations and channels the same as you do through the console. For example, you specify ad insertion behavior and mapping information for the origin server and the ad decision server (ADS).</p>
  x-logo:
    url: https://api.apis.guru/v2/cache/logo/https_twitter.com_awscloud_profile_image.png
    backgroundColor: '#FFFFFF'
  termsOfService: https://aws.amazon.com/service-terms/
  contact:
    name: Mike Ralphson
    email: mike.ralphson@gmail.com
    url: https://github.com/mermade/aws2openapi
    x-twitter: PermittedSoc
  license:
    name: Apache 2.0 License
    url: http://www.apache.org/licenses/
  x-providerName: amazonaws.com
  x-serviceName: mediatailor
  x-aws-signingName: mediatailor
  x-origin:
  - contentType: application/json
    url: https://raw.githubusercontent.com/aws/aws-sdk-js/master/apis/mediatailor-2018-04-23.normal.json
    converter:
      url: https://github.com/mermade/aws2openapi
      version: 1.0.0
    x-apisguru-driver: external
  x-apiClientRegistration:
    url: https://portal.aws.amazon.com/gp/aws/developer/registration/index.html?nc2=h_ct
  x-apisguru-categories:
  - cloud
  x-preferred: true
servers:
- url: http://api.mediatailor.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaTailor multi-region endpoint
- url: https://api.mediatailor.{region}.amazonaws.com
  variables:
    region:
      description: The AWS region
      enum:
      - us-east-1
      - us-east-2
      - us-west-1
      - us-west-2
      - us-gov-west-1
      - us-gov-east-1
      - ca-central-1
      - eu-north-1
      - eu-west-1
      - eu-west-2
      - eu-west-3
      - eu-central-1
      - eu-south-1
      - af-south-1
      - ap-northeast-1
      - ap-northeast-2
      - ap-northeast-3
      - ap-southeast-1
      - ap-southeast-2
      - ap-east-1
      - ap-south-1
      - sa-east-1
      - me-south-1
      default: us-east-1
  description: The MediaTailor multi-region endpoint
- url: http://api.mediatailor.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaTailor endpoint for China (Beijing) and China (Ningxia)
- url: https://api.mediatailor.{region}.amazonaws.com.cn
  variables:
    region:
      description: The AWS region
      enum:
      - cn-north-1
      - cn-northwest-1
      default: cn-north-1
  description: The MediaTailor endpoint for China (Beijing) and China (Ningxia)
security:
- hmac: []
tags:
- name: Alerts#resourceArn
paths:
  /alerts#resourceArn:
    parameters:
    - $ref: '#/components/parameters/X-Amz-Content-Sha256'
    - $ref: '#/components/parameters/X-Amz-Date'
    - $ref: '#/components/parameters/X-Amz-Algorithm'
    - $ref: '#/components/parameters/X-Amz-Credential'
    - $ref: '#/components/parameters/X-Amz-Security-Token'
    - $ref: '#/components/parameters/X-Amz-Signature'
    - $ref: '#/components/parameters/X-Amz-SignedHeaders'
    get:
      operationId: ListAlerts
      description: Lists the alerts that are associated with a MediaTailor channel assembly resource.
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListAlertsResponse'
              examples:
                ListAlerts200Example:
                  summary: Default ListAlerts 200 response
                  x-microcks-default: true
                  value:
                    Items: example-value
                    NextToken: example-value
      parameters:
      - name: maxResults
        in: query
        required: false
        description: The maximum number of alerts that you want MediaTailor to return in response to the current request. If there are more than <code>MaxResults</code> alerts, use the value of <code>NextToken</code> in the response to get the next page of results.
        schema:
          type: integer
          minimum: 1
          maximum: 100
      - name: nextToken
        in: query
        required: false
        description: Pagination token returned by the list request when results exceed the maximum allowed. Use the token to fetch the next page of results.
        schema:
          type: string
      - name: resourceArn
        in: query
        required: true
        description: The Amazon Resource Name (ARN) of the resource.
        schema:
          type: string
      - name: MaxResults
        in: query
        schema:
          type: string
        description: Pagination limit
        required: false
      - name: NextToken
        in: query
        schema:
          type: string
        description: Pagination token
        required: false
      summary: Amazon MediaTailor List Alerts
      x-microcks-operation:
        delay: 0
        dispatcher: FALLBACK
      tags:
      - Alerts#resourceArn
components:
  schemas:
    __listOfAlert:
      type: array
      items:
        $ref: '#/components/schemas/Alert'
    __listOf__string:
      type: array
      items:
        $ref: '#/components/schemas/__string'
    __timestampUnix:
      type: string
      format: date-time
    ListAlertsResponse:
      type: object
      properties:
        Items:
          allOf:
          - $ref: '#/components/schemas/__listOfAlert'
          - description: A list of alerts that are associated with this resource.
        NextToken:
          allOf:
          - $ref: '#/components/schemas/__string'
          - description: Pagination token returned by the list request when results exceed the maximum allowed. Use the token to fetch the next page of results.
    Alert:
      type: object
      required:
      - AlertCode
      - AlertMessage
      - LastModifiedTime
      - RelatedResourceArns
      - ResourceArn
      properties:
        AlertCode:
          allOf:
          - $ref: '#/components/schemas/__string'
          - description: The code for the alert. For example, <code>NOT_PROCESSED</code>.
        AlertMessage:
          allOf:
          - $ref: '#/components/schemas/__string'
          - description: If an alert is generated for a resource, an explanation of the reason for the alert.
        LastModifiedTime:
          allOf:
          - $ref: '#/components/schemas/__timestampUnix'
          - description: The timestamp when the alert was last modified.
        RelatedResourceArns:
          allOf:
          - $ref: '#/components/schemas/__listOf__string'
          - description: The Amazon Resource Names (ARNs) related to this alert.
        ResourceArn:
          allOf:
          - $ref: '#/components/schemas/__string'
          - description: The Amazon Resource Name (ARN) of the resource.
      description: Alert configuration parameters.
    __string:
      type: string
  parameters:
    X-Amz-Date:
      name: X-Amz-Date
      in: header
      schema:
        type: string
      required: false
    X-Amz-Security-Token:
      name: X-Amz-Security-Token
      in: header
      schema:
        type: string
      required: false
    X-Amz-Signature:
      name: X-Amz-Signature
      in: header
      schema:
        type: string
      required: false
    X-Amz-SignedHeaders:
      name: X-Amz-SignedHeaders
      in: header
      schema:
        type: string
      required: false
    X-Amz-Content-Sha256:
      name: X-Amz-Content-Sha256
      in: header
      schema:
        type: string
      required: false
    X-Amz-Algorithm:
      name: X-Amz-Algorithm
      in: header
      schema:
        type: string
      required: false
    X-Amz-Credential:
      name: X-Amz-Credential
      in: header
      schema:
        type: string
      required: false
  securitySchemes:
    hmac:
      type: apiKey
      name: Authorization
      in: header
      description: Amazon Signature authorization v4
      x-amazon-apigateway-authtype: awsSigv4
externalDocs:
  description: Amazon Web Services documentation
  url: https://docs.aws.amazon.com/mediatailor/
x-hasEquivalentPaths: true
